apiVersion: v1
kind: Secret
metadata:
  name: git
  labels:
    app: {{ template "airflow.name" . }}
    chart: {{ template "airflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{- if .Values.airflow.dags.git.enable_ssh }}
  gitSshKey: {{ .Values.airflow.dags.git.ssh | b64enc | quote }}
  {{- end }}
  {{- if .Values.airflow.dags.git.username }}
  GIT_SYNC_USERNAME: {{ .Values.airflow.dags.git.username | b64enc | quote }}
  {{- end }}
  {{- if .Values.airflow.dags.git.password }}
  GIT_SYNC_PASSWORD: {{ .Values.airflow.dags.git.password | b64enc | quote }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "airflow.fullname" . }}-env
  labels:
    app: {{ template "airflow.name" . }}
    chart: {{ template "airflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  FERNET_KEY: {{ .Values.airflow.fernet_key | b64enc | quote }}
  AIRFLOW__CORE__SQL_ALCHEMY_CONN: {{ printf "postgresql+psycopg2://%s:%s@%s:%s/%s" .Values.postgresql.postgresqlUsername .Values.postgresql.postgresqlPassword (include "airflow.postgresql.fullname" .) "5432" .Values.postgresql.postgresqlDatabase | b64enc | quote }}
  AIRFLOW_HOME: {{ printf "/usr/local/airflow" | b64enc | quote }}
  AIRFLOW__CORE__EXECUTOR: S3ViZXJuZXRlc0V4ZWN1dG9y
  {{- if and (not .Values.airflow.dags.persistence.enabled) (not .Values.airflow.dags.git.enable_ssh) }}
  {{- if .Values.airflow.dags.git.username }}
  AIRFLOW__KUBERNETES__GIT_USER: {{ .Values.airflow.dags.git.username | b64enc | quote }}
  {{- end }}
  {{- if .Values.airflow.dags.git.password }}
  AIRFLOW__KUBERNETES__GIT_PASSWORD: {{ .Values.airflow.dags.git.password | b64enc | quote }}
  {{- end }}
  {{- end }}
  POSTGRES_DB: {{ .Values.postgresql.postgresqlDatabase | b64enc | quote  }}
  POSTGRES_USER: {{ .Values.postgresql.postgresqlUsername | b64enc | quote  }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}